[package]
name = "repro-async-std"
version = "0.1.0"
edition = "2021"

[dependencies]
async-smtp = { version = "0.9", default-features = false, features = ["runtime-async-std"] }
async-std = { version = "1.12",  default-features = false, features = ["attributes"]}